[package]
name = "enchato"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "0.13"
actix-web = "4"
actix-web-actors = "4"
env_logger = "0.10"
nanoid = "0.4"
bytestring = "1.3"
